[package]
name = "inline-c"
version = "0.1.0"
authors = ["Ivan Enderlin <ivan@mnt.io>"]
edition = "2018"

[dependencies]
tempfile = "3.1"
inline-c-macro = { path = "./macros/" }
regex = "1.4"
lazy_static = "1.4"

[workspace]
members = [
    "macros",
]